#! /bin/sh

sxhkd -c ~/etc/sxhkdrc &

bspc monitor -d i ii iii iv v vi vii viii ix x

bspc config border_width 1
bspc config window_gap 3
bspc config right_padding -3
bspc config left_padding -3
bspc config bottom_padding -3

bspc config focused_border_color '#458588'
bspc config split_ratio 0.52
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config directional_focus_tightness low

bspc rule -a feh state=floating
bspc rule -a gimp state=floating
bspc rule -a display state=floating
